steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/voice-ai', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/voice-ai']

  # Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'voice-ai'
    - '--image'
    - 'gcr.io/$PROJECT_ID/voice-ai'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--update-secrets'
    - 'CUSTOM_PORT=CUSTOM_PORT:latest'  # Use CUSTOM_PORT instead of PORT
    - '--update-secrets'
    - 'CRED_JSON=CRED_JSON:latest'


images:
- 'gcr.io/$PROJECT_ID/voice-ai'
